from PyQt5 import QtCore, QtGui, QtWidgets
import icons

class Ui_AddStudentForm(object):
    def setupUi(self, AddStudentForm):
        AddStudentForm.setObjectName("AddStudentForm")
        AddStudentForm.resize(328, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddStudentForm.setWindowIcon(icon)
        self.AddStudentTabSwitcher = QtWidgets.QTabWidget(AddStudentForm)
        self.AddStudentTabSwitcher.setGeometry(QtCore.QRect(0, 0, 325, 300))
        self.AddStudentTabSwitcher.setObjectName("AddStudentTabSwitcher")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.CancelButton2 = QtWidgets.QPushButton(self.tab)
        self.CancelButton2.setGeometry(QtCore.QRect(220, 230, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.CancelButton2.setFont(font)
        self.CancelButton2.setObjectName("CancelButton2")
        self.NextButton = QtWidgets.QPushButton(self.tab)
        self.NextButton.setGeometry(QtCore.QRect(140, 230, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.NextButton.setFont(font)
        self.NextButton.setObjectName("NextButton")
        self.NameInput = QtWidgets.QLineEdit(self.tab)
        self.NameInput.setGeometry(QtCore.QRect(130, 20, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.NameInput.setFont(font)
        self.NameInput.setObjectName("NameInput")
        self.NameLabel = QtWidgets.QLabel(self.tab)
        self.NameLabel.setGeometry(QtCore.QRect(20, 20, 50, 15))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 75, 15))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 50, 15))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.DepartmentComboBox = QtWidgets.QComboBox(self.tab)
        self.DepartmentComboBox.setGeometry(QtCore.QRect(130, 110, 151, 22))
        self.DepartmentComboBox.setObjectName("DepartmentComboBox")
        self.DepartmentComboBox.addItem("")
        self.DepartmentComboBox.addItem("")
        self.DepartmentComboBox.addItem("")
        self.DepartmentComboBox.addItem("")
        self.DepartmentComboBox.addItem("")
        self.YearComboBox = QtWidgets.QComboBox(self.tab)
        self.YearComboBox.setGeometry(QtCore.QRect(220, 80, 60, 20))
        self.YearComboBox.setObjectName("YearComboBox")
        self.YearComboBox.addItem("")
        self.YearComboBox.addItem("")
        self.YearComboBox.addItem("")
        self.YearComboBox.addItem("")
        self.PhoneInput = QtWidgets.QLineEdit(self.tab)
        self.PhoneInput.setGeometry(QtCore.QRect(130, 140, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.PhoneInput.setFont(font)
        self.PhoneInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.PhoneInput.setObjectName("PhoneInput")
        self.AddressInput = QtWidgets.QLineEdit(self.tab)
        self.AddressInput.setGeometry(QtCore.QRect(130, 170, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.AddressInput.setFont(font)
        self.AddressInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.AddressInput.setObjectName("AddressInput")
        self.GenderComboBox = QtWidgets.QComboBox(self.tab)
        self.GenderComboBox.setGeometry(QtCore.QRect(220, 50, 60, 20))
        self.GenderComboBox.setObjectName("GenderComboBox")
        self.GenderComboBox.addItem("")
        self.GenderComboBox.addItem("")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 50, 50, 15))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.AddStudentTabSwitcher.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.CancelButton = QtWidgets.QPushButton(self.tab_2)
        self.CancelButton.setGeometry(QtCore.QRect(220, 230, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.CancelButton.setFont(font)
        self.CancelButton.setObjectName("CancelButton")
        self.AddStudentButton = QtWidgets.QPushButton(self.tab_2)
        self.AddStudentButton.setGeometry(QtCore.QRect(140, 230, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.AddStudentButton.setFont(font)
        self.AddStudentButton.setObjectName("AddStudentButton")
        self.BackButton = QtWidgets.QPushButton(self.tab_2)
        self.BackButton.setGeometry(QtCore.QRect(60, 230, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 100, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 130, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 160, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 190, 200, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.MathInput = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.MathInput.setGeometry(QtCore.QRect(220, 10, 62, 22))
        self.MathInput.setObjectName("MathInput")
        self.DSInput = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.DSInput.setGeometry(QtCore.QRect(220, 40, 62, 22))
        self.DSInput.setObjectName("DSInput")
        self.ISInput = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.ISInput.setGeometry(QtCore.QRect(220, 70, 62, 22))
        self.ISInput.setObjectName("ISInput")
        self.OOPInput = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.OOPInput.setGeometry(QtCore.QRect(220, 100, 62, 22))
        self.OOPInput.setObjectName("OOPInput")
        self.PMInput = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.PMInput.setGeometry(QtCore.QRect(220, 130, 62, 22))
        self.PMInput.setObjectName("PMInput")
        self.BAInput = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.BAInput.setGeometry(QtCore.QRect(220, 160, 62, 22))
        self.BAInput.setObjectName("BAInput")
        self.TWInput = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.TWInput.setGeometry(QtCore.QRect(220, 190, 62, 22))
        self.TWInput.setObjectName("TWInput")
        self.AddStudentTabSwitcher.addTab(self.tab_2, "")

        self.retranslateUi(AddStudentForm)
        self.AddStudentTabSwitcher.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AddStudentForm)

    def retranslateUi(self, AddStudentForm):
        _translate = QtCore.QCoreApplication.translate
        AddStudentForm.setWindowTitle(_translate("AddStudentForm", "Add Student"))
        self.CancelButton2.setText(_translate("AddStudentForm", "Cancel"))
        self.NextButton.setText(_translate("AddStudentForm", "Next"))
        self.NameLabel.setText(_translate("AddStudentForm", "Name"))
        self.label_2.setText(_translate("AddStudentForm", "Department"))
        self.label_3.setText(_translate("AddStudentForm", "Year"))
        self.label_4.setText(_translate("AddStudentForm", "Phone Number"))
        self.label_5.setText(_translate("AddStudentForm", "Address"))
        self.DepartmentComboBox.setItemText(0, _translate("AddStudentForm", "Computer system"))
        self.DepartmentComboBox.setItemText(1, _translate("AddStudentForm", "Information Technology"))
        self.DepartmentComboBox.setItemText(2, _translate("AddStudentForm", "Information systems"))
        self.DepartmentComboBox.setItemText(3, _translate("AddStudentForm", "Software Engineering"))
        self.DepartmentComboBox.setItemText(4, _translate("AddStudentForm", "Bio-Informatics"))
        self.YearComboBox.setItemText(0, _translate("AddStudentForm", "1"))
        self.YearComboBox.setItemText(1, _translate("AddStudentForm", "2"))
        self.YearComboBox.setItemText(2, _translate("AddStudentForm", "3"))
        self.YearComboBox.setItemText(3, _translate("AddStudentForm", "4"))
        self.GenderComboBox.setItemText(0, _translate("AddStudentForm", "Male"))
        self.GenderComboBox.setItemText(1, _translate("AddStudentForm", "Female"))
        self.label_13.setText(_translate("AddStudentForm", "Gender"))
        self.AddStudentTabSwitcher.setTabText(self.AddStudentTabSwitcher.indexOf(self.tab), _translate("AddStudentForm", "Student Details"))
        self.CancelButton.setText(_translate("AddStudentForm", "Cancel"))
        self.AddStudentButton.setText(_translate("AddStudentForm", "Finish"))
        self.BackButton.setText(_translate("AddStudentForm", "Back"))
        self.label_6.setText(_translate("AddStudentForm", "Maths Grade"))
        self.label_7.setText(_translate("AddStudentForm", "Discreet Structers Grade"))
        self.label_8.setText(_translate("AddStudentForm", "Information System Grade"))
        self.label_9.setText(_translate("AddStudentForm", "Object Oriented Programming"))
        self.label_10.setText(_translate("AddStudentForm", "Project Management Grade"))
        self.label_11.setText(_translate("AddStudentForm", "Buissness administration Grade"))
        self.label_12.setText(_translate("AddStudentForm", "Technical Writing Grade"))
        self.AddStudentTabSwitcher.setTabText(self.AddStudentTabSwitcher.indexOf(self.tab_2), _translate("AddStudentForm", "Student Grades"))
