from PyQt5 import QtCore, QtGui, QtWidgets
import icons

class Ui_MainProgram(object):
    def setupUi(self, MainProgram):
        MainProgram.setObjectName("MainProgram")
        MainProgram.resize(948, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainProgram.sizePolicy().hasHeightForWidth())
        MainProgram.setSizePolicy(sizePolicy)
        MainProgram.setMinimumSize(QtCore.QSize(948, 700))
        MainProgram.setMaximumSize(QtCore.QSize(948, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainProgram.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainProgram)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.MainTabSwitcher = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTabSwitcher.setGeometry(QtCore.QRect(0, 0, 950, 660))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainTabSwitcher.sizePolicy().hasHeightForWidth())
        self.MainTabSwitcher.setSizePolicy(sizePolicy)
        self.MainTabSwitcher.setObjectName("MainTabSwitcher")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.StudentDetailsTable = QtWidgets.QTableWidget(self.tab)
        self.StudentDetailsTable.setGeometry(QtCore.QRect(0, 0, 950, 640))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StudentDetailsTable.sizePolicy().hasHeightForWidth())
        self.StudentDetailsTable.setSizePolicy(sizePolicy)
        self.StudentDetailsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.StudentDetailsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.StudentDetailsTable.setAlternatingRowColors(False)
        self.StudentDetailsTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.StudentDetailsTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.StudentDetailsTable.setObjectName("StudentDetailsTable")
        self.StudentDetailsTable.setColumnCount(8)
        self.StudentDetailsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StudentDetailsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentDetailsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentDetailsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentDetailsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentDetailsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentDetailsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentDetailsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentDetailsTable.setHorizontalHeaderItem(7, item)
        self.StudentDetailsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.StudentDetailsTable.horizontalHeader().setDefaultSectionSize(150)
        self.StudentDetailsTable.horizontalHeader().setMinimumSectionSize(20)
        self.StudentDetailsTable.horizontalHeader().setSortIndicatorShown(True)
        self.StudentDetailsTable.horizontalHeader().setStretchLastSection(True)
        self.StudentDetailsTable.verticalHeader().setVisible(False)
        self.StudentDetailsTable.verticalHeader().setCascadingSectionResizes(True)
        self.StudentDetailsTable.verticalHeader().setSortIndicatorShown(True)
        self.StudentDetailsTable.verticalHeader().setStretchLastSection(False)
        self.MainTabSwitcher.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.StudentGradesTable = QtWidgets.QTableWidget(self.tab_2)
        self.StudentGradesTable.setGeometry(QtCore.QRect(0, 0, 950, 640))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StudentGradesTable.sizePolicy().hasHeightForWidth())
        self.StudentGradesTable.setSizePolicy(sizePolicy)
        self.StudentGradesTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.StudentGradesTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.StudentGradesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.StudentGradesTable.setObjectName("StudentGradesTable")
        self.StudentGradesTable.setColumnCount(10)
        self.StudentGradesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.StudentGradesTable.setHorizontalHeaderItem(9, item)
        self.StudentGradesTable.horizontalHeader().setCascadingSectionResizes(True)
        self.StudentGradesTable.horizontalHeader().setDefaultSectionSize(150)
        self.StudentGradesTable.horizontalHeader().setMinimumSectionSize(20)
        self.StudentGradesTable.horizontalHeader().setSortIndicatorShown(True)
        self.StudentGradesTable.horizontalHeader().setStretchLastSection(True)
        self.StudentGradesTable.verticalHeader().setVisible(False)
        self.StudentGradesTable.verticalHeader().setCascadingSectionResizes(True)
        self.StudentGradesTable.verticalHeader().setSortIndicatorShown(True)
        self.StudentGradesTable.verticalHeader().setStretchLastSection(False)
        self.MainTabSwitcher.addTab(self.tab_2, "")
        MainProgram.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainProgram)
        self.toolBar.setObjectName("toolBar")
        MainProgram.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.AddStudentAction = QtWidgets.QAction(MainProgram)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddStudentAction.setIcon(icon1)
        self.AddStudentAction.setObjectName("AddStudentAction")
        self.LoadDataAction = QtWidgets.QAction(MainProgram)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.LoadDataAction.setIcon(icon2)
        self.LoadDataAction.setObjectName("LoadDataAction")
        self.SearchStudentAction = QtWidgets.QAction(MainProgram)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.SearchStudentAction.setIcon(icon3)
        self.SearchStudentAction.setObjectName("SearchStudentAction")
        self.DeleteStudentAction = QtWidgets.QAction(MainProgram)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.DeleteStudentAction.setIcon(icon4)
        self.DeleteStudentAction.setObjectName("DeleteStudentAction")
        self.EditStudentAction = QtWidgets.QAction(MainProgram)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditStudentAction.setIcon(icon5)
        self.EditStudentAction.setObjectName("EditStudentAction")
        self.toolBar.addAction(self.AddStudentAction)
        self.toolBar.addAction(self.SearchStudentAction)
        self.toolBar.addAction(self.EditStudentAction)
        self.toolBar.addAction(self.LoadDataAction)
        self.toolBar.addAction(self.DeleteStudentAction)

        self.retranslateUi(MainProgram)
        self.MainTabSwitcher.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainProgram)

    def retranslateUi(self, MainProgram):
        _translate = QtCore.QCoreApplication.translate
        MainProgram.setWindowTitle(_translate("MainProgram", "College Information System"))
        self.StudentDetailsTable.setSortingEnabled(True)
        item = self.StudentDetailsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainProgram", "ID"))
        item = self.StudentDetailsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainProgram", "Name"))
        item = self.StudentDetailsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainProgram", "Gender"))
        item = self.StudentDetailsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainProgram", "Department"))
        item = self.StudentDetailsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainProgram", "Year"))
        item = self.StudentDetailsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainProgram", "Phone"))
        item = self.StudentDetailsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainProgram", "Address"))
        item = self.StudentDetailsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainProgram", "Grade Percent"))
        self.MainTabSwitcher.setTabText(self.MainTabSwitcher.indexOf(self.tab), _translate("MainProgram", "Students Details"))
        self.StudentGradesTable.setToolTip(_translate("MainProgram", "<html><head/><body><p><br/>DS = Discrete Maths</p><p>IS = Information Systems</p><p>OOP = Object-Oriented Programming</p><p>PM = Project Management</p><p>BA = Buissness Administration</p><p>TW = Technical Writing</p></body></html>"))
        self.StudentGradesTable.setSortingEnabled(True)
        item = self.StudentGradesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainProgram", "ID"))
        item = self.StudentGradesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainProgram", "Name"))
        item = self.StudentGradesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainProgram", "Maths III"))
        item = self.StudentGradesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainProgram", "DS"))
        item = self.StudentGradesTable.horizontalHeaderItem(4)
        item.setText(_translate("MainProgram", "IS"))
        item = self.StudentGradesTable.horizontalHeaderItem(5)
        item.setText(_translate("MainProgram", "OOP"))
        item = self.StudentGradesTable.horizontalHeaderItem(6)
        item.setText(_translate("MainProgram", "PM"))
        item = self.StudentGradesTable.horizontalHeaderItem(7)
        item.setText(_translate("MainProgram", "BA"))
        item = self.StudentGradesTable.horizontalHeaderItem(8)
        item.setText(_translate("MainProgram", "TW"))
        item = self.StudentGradesTable.horizontalHeaderItem(9)
        item.setText(_translate("MainProgram", "Grade Percent"))
        self.MainTabSwitcher.setTabText(self.MainTabSwitcher.indexOf(self.tab_2), _translate("MainProgram", "Student Grades"))
        self.toolBar.setWindowTitle(_translate("MainProgram", "toolBar"))
        self.AddStudentAction.setText(_translate("MainProgram", "Add Student"))
        self.AddStudentAction.setToolTip(_translate("MainProgram", "Add Student"))
        self.LoadDataAction.setText(_translate("MainProgram", "Load Data"))
        self.LoadDataAction.setToolTip(_translate("MainProgram", "Refresh Data"))
        self.SearchStudentAction.setText(_translate("MainProgram", "Search Student"))
        self.SearchStudentAction.setToolTip(_translate("MainProgram", "Search Student"))
        self.DeleteStudentAction.setText(_translate("MainProgram", "Delete Student"))
        self.DeleteStudentAction.setToolTip(_translate("MainProgram", "Delete student"))
        self.EditStudentAction.setText(_translate("MainProgram", "EditStudent"))