from PyQt5 import QtCore, QtGui, QtWidgets
import icons

class Ui_SearchStudentResults(object):
    def setupUi(self, SearchStudentResults):
        SearchStudentResults.setObjectName("SearchStudentResults")
        SearchStudentResults.resize(325, 458)
        SearchStudentResults.setMinimumSize(QtCore.QSize(325, 458))
        SearchStudentResults.setMaximumSize(QtCore.QSize(325, 458))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchStudentResults.setWindowIcon(icon)
        self.SearchStudentTabSwitcher = QtWidgets.QTabWidget(SearchStudentResults)
        self.SearchStudentTabSwitcher.setGeometry(QtCore.QRect(0, 0, 325, 461))
        self.SearchStudentTabSwitcher.setObjectName("SearchStudentTabSwitcher")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.ExitButton1 = QtWidgets.QPushButton(self.tab)
        self.ExitButton1.setGeometry(QtCore.QRect(240, 390, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.ExitButton1.setFont(font)
        self.ExitButton1.setObjectName("ExitButton1")
        self.NextButton = QtWidgets.QPushButton(self.tab)
        self.NextButton.setGeometry(QtCore.QRect(160, 390, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.NextButton.setFont(font)
        self.NextButton.setObjectName("NextButton")
        self.NameLabel = QtWidgets.QLabel(self.tab)
        self.NameLabel.setGeometry(QtCore.QRect(20, 40, 290, 15))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 290, 15))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 290, 15))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 280, 290, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 340, 290, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 100, 290, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.NameOutput = QtWidgets.QLabel(self.tab)
        self.NameOutput.setGeometry(QtCore.QRect(20, 70, 290, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.NameOutput.setFont(font)
        self.NameOutput.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.NameOutput.setAutoFillBackground(False)
        self.NameOutput.setObjectName("NameOutput")
        self.GenderOutput = QtWidgets.QLabel(self.tab)
        self.GenderOutput.setGeometry(QtCore.QRect(20, 130, 290, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.GenderOutput.setFont(font)
        self.GenderOutput.setObjectName("GenderOutput")
        self.YearOutput = QtWidgets.QLabel(self.tab)
        self.YearOutput.setGeometry(QtCore.QRect(20, 190, 290, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.YearOutput.setFont(font)
        self.YearOutput.setObjectName("YearOutput")
        self.DepartmentOutput = QtWidgets.QLabel(self.tab)
        self.DepartmentOutput.setGeometry(QtCore.QRect(20, 250, 290, 15))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.DepartmentOutput.setFont(font)
        self.DepartmentOutput.setObjectName("DepartmentOutput")
        self.PhoneOutput = QtWidgets.QLabel(self.tab)
        self.PhoneOutput.setGeometry(QtCore.QRect(20, 310, 290, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.PhoneOutput.setFont(font)
        self.PhoneOutput.setObjectName("PhoneOutput")
        self.AddressOutput = QtWidgets.QLabel(self.tab)
        self.AddressOutput.setGeometry(QtCore.QRect(20, 370, 290, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.AddressOutput.setFont(font)
        self.AddressOutput.setObjectName("AddressOutput")
        self.SearchInputForSearch = QtWidgets.QLineEdit(self.tab)
        self.SearchInputForSearch.setGeometry(QtCore.QRect(20, 10, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.SearchInputForSearch.setFont(font)
        self.SearchInputForSearch.setObjectName("SearchInputForSearch")
        self.SearchButtonForSearch = QtWidgets.QPushButton(self.tab)
        self.SearchButtonForSearch.setGeometry(QtCore.QRect(190, 10, 70, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.SearchButtonForSearch.setFont(font)
        self.SearchButtonForSearch.setObjectName("SearchButtonForSearch")
        self.SearchStudentTabSwitcher.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.ExitButton2 = QtWidgets.QPushButton(self.tab_2)
        self.ExitButton2.setGeometry(QtCore.QRect(240, 390, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ExitButton2.setFont(font)
        self.ExitButton2.setObjectName("ExitButton2")
        self.BackButton = QtWidgets.QPushButton(self.tab_2)
        self.BackButton.setGeometry(QtCore.QRect(160, 390, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.DSGradeOutput = QtWidgets.QLabel(self.tab_2)
        self.DSGradeOutput.setGeometry(QtCore.QRect(20, 100, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.DSGradeOutput.setFont(font)
        self.DSGradeOutput.setWordWrap(False)
        self.DSGradeOutput.setObjectName("DSGradeOutput")
        self.ISGradeOutput = QtWidgets.QLabel(self.tab_2)
        self.ISGradeOutput.setGeometry(QtCore.QRect(20, 160, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.ISGradeOutput.setFont(font)
        self.ISGradeOutput.setWordWrap(False)
        self.ISGradeOutput.setObjectName("ISGradeOutput")
        self.OOPGradeOutput = QtWidgets.QLabel(self.tab_2)
        self.OOPGradeOutput.setGeometry(QtCore.QRect(20, 220, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.OOPGradeOutput.setFont(font)
        self.OOPGradeOutput.setWordWrap(False)
        self.OOPGradeOutput.setObjectName("OOPGradeOutput")
        self.PMGradeOutput = QtWidgets.QLabel(self.tab_2)
        self.PMGradeOutput.setGeometry(QtCore.QRect(20, 280, 250, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.PMGradeOutput.setFont(font)
        self.PMGradeOutput.setWordWrap(False)
        self.PMGradeOutput.setObjectName("PMGradeOutput")
        self.BAGradeOutput = QtWidgets.QLabel(self.tab_2)
        self.BAGradeOutput.setGeometry(QtCore.QRect(20, 340, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.BAGradeOutput.setFont(font)
        self.BAGradeOutput.setWordWrap(False)
        self.BAGradeOutput.setObjectName("BAGradeOutput")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 370, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.MathGradeOutput = QtWidgets.QLabel(self.tab_2)
        self.MathGradeOutput.setGeometry(QtCore.QRect(20, 40, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.MathGradeOutput.setFont(font)
        self.MathGradeOutput.setWordWrap(False)
        self.MathGradeOutput.setObjectName("MathGradeOutput")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(20, 70, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(20, 130, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(20, 190, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(20, 250, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(20, 310, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.TWGradeOutput = QtWidgets.QLabel(self.tab_2)
        self.TWGradeOutput.setGeometry(QtCore.QRect(20, 400, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.TWGradeOutput.setFont(font)
        self.TWGradeOutput.setWordWrap(False)
        self.TWGradeOutput.setObjectName("TWGradeOutput")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(210, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.TotalGradeOutput = QtWidgets.QLabel(self.tab_2)
        self.TotalGradeOutput.setGeometry(QtCore.QRect(210, 30, 105, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.TotalGradeOutput.setFont(font)
        self.TotalGradeOutput.setWordWrap(False)
        self.TotalGradeOutput.setObjectName("TotalGradeOutput")
        self.SearchStudentTabSwitcher.addTab(self.tab_2, "")

        self.retranslateUi(SearchStudentResults)
        self.SearchStudentTabSwitcher.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SearchStudentResults)

    def retranslateUi(self, SearchStudentResults):
        _translate = QtCore.QCoreApplication.translate
        SearchStudentResults.setWindowTitle(_translate("SearchStudentResults", "Search Student"))
        self.ExitButton1.setText(_translate("SearchStudentResults", "Exit"))
        self.NextButton.setText(_translate("SearchStudentResults", "Next"))
        self.NameLabel.setText(_translate("SearchStudentResults", "Name"))
        self.label_2.setText(_translate("SearchStudentResults", "Department"))
        self.label_3.setText(_translate("SearchStudentResults", "Year"))
        self.label_4.setText(_translate("SearchStudentResults", "Phone Number"))
        self.label_5.setText(_translate("SearchStudentResults", "Address"))
        self.label_13.setText(_translate("SearchStudentResults", "Gender"))
        self.NameOutput.setText(_translate("SearchStudentResults", ""))
        self.GenderOutput.setText(_translate("SearchStudentResults", ""))
        self.YearOutput.setText(_translate("SearchStudentResults", ""))
        self.DepartmentOutput.setText(_translate("SearchStudentResults", ""))
        self.PhoneOutput.setText(_translate("SearchStudentResults", ""))
        self.AddressOutput.setText(_translate("SearchStudentResults", ""))
        self.SearchInputForSearch.setPlaceholderText(_translate("SearchStudentResults", "ID"))
        self.SearchButtonForSearch.setText(_translate("SearchStudentResults", "Search"))
        self.SearchStudentTabSwitcher.setTabText(self.SearchStudentTabSwitcher.indexOf(self.tab), _translate("SearchStudentResults", "Student Details"))
        self.ExitButton2.setText(_translate("SearchStudentResults", "Exit"))
        self.BackButton.setText(_translate("SearchStudentResults", "Back"))
        self.label_6.setText(_translate("SearchStudentResults", "Maths Grade"))
        self.DSGradeOutput.setText(_translate("SearchStudentResults", ""))
        self.ISGradeOutput.setText(_translate("SearchStudentResults", ""))
        self.OOPGradeOutput.setText(_translate("SearchStudentResults", ""))
        self.PMGradeOutput.setText(_translate("SearchStudentResults", ""))
        self.BAGradeOutput.setText(_translate("SearchStudentResults", ""))
        self.label_12.setText(_translate("SearchStudentResults", "Technical Writing Grade"))
        self.MathGradeOutput.setText(_translate("SearchStudentResults", ""))
        self.label_20.setText(_translate("SearchStudentResults", "Discreet Structers Grade"))
        self.label_21.setText(_translate("SearchStudentResults", "Information System Grade"))
        self.label_22.setText(_translate("SearchStudentResults", "Object Oriented Programming"))
        self.label_23.setText(_translate("SearchStudentResults", "Project Management Grade"))
        self.label_24.setText(_translate("SearchStudentResults", "Buissness administration Grade"))
        self.TWGradeOutput.setText(_translate("SearchStudentResults", ""))
        self.label_7.setText(_translate("SearchStudentResults", "Total Grade"))
        self.TotalGradeOutput.setText(_translate("SearchStudentResults", ""))
        self.SearchStudentTabSwitcher.setTabText(self.SearchStudentTabSwitcher.indexOf(self.tab_2), _translate("SearchStudentResults", "Student Grades"))
